export enum MotifsEnum {
  INSULTES = 'INSULTES',
  SPAM_OU_PUBLICITE = 'SPAM_OU_PUBLICITE',
  HORS_SUJET = 'HORS_SUJET',
  HARCELEMENT_OU_INTIMIDATION = 'HARCELEMENT_OU_INTIMIDATION',
  CONTENU_VULGAIRE = 'CONTENU_VULGAIRE',
  INFORMATION_PERSONNELLE = 'INFORMATION_PERSONNELLE',
  USURPATION_IDENTITE = 'USURPATION_IDENTITE',
  INCITATION_A_LA_HAINE = 'INCITATION_A_LA_HAINE',
  VIOLATION_DROITS_AUTEUR = 'VIOLATION_DROITS_AUTEUR',
  AUTRES = 'AUTRES'
}
